### ISSUE TITLE
The process was terminated due to an unhandled exception

### ISSUE THREAD

**Issue by sbenito84** [fvanroie/DscDashboard#4]
Hi,
First, Congratulations for your work!

I'm trying to use it, but I have problem with application. My environment is Windows 2019, IIS, sql 2017, net framework 4.7, powershell 5.1...

Application: universaldashboard.server.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.ObjectDisposedException
   at System.Runtime.InteropServices.SafeHandle.DangerousAddRef(Boolean ByRef)
   at System.StubHelpers.StubHelpers.SafeHandleAddRef(System.Runtime.InteropServices.SafeHandle, Boolean ByRef)
   at Microsoft.AspNetCore.Server.Kestrel.Transport.Libuv.Internal.Networking.LibuvFunctions+NativeMethods.uv_async_send(Microsoft.AspNetCore.Server.Kestrel.Transport.Libuv.Internal.Networking.UvAsyncHandle)
   at Microsoft.AspNetCore.Server.Kestrel.Transport.Libuv.Internal.Networking.LibuvFunctions.async_send(Microsoft.AspNetCore.Server.Kestrel.Transport.Libuv.Internal.Networking.UvAsyncHandle)
   at Microsoft.AspNetCore.Server.Kestrel.Transport.Libuv.Internal.LibuvThread.PostCloseHandle(System.Action`1<IntPtr>, IntPtr)
   at Microsoft.AspNetCore.Server.Kestrel.Transport.Libuv.Internal.Networking.UvHandle.ReleaseHandle()
   at Microsoft.AspNetCore.Server.Kestrel.Transport.Libuv.Internal.Networking.UvStreamHandle.ReleaseHandle()
   at System.Runtime.InteropServices.SafeHandle.InternalFinalize()
   at System.Runtime.InteropServices.SafeHandle.Finalize()

Any idea? Thanks!

**Comment by sbenito84** [comment]
Resolved. All files had not been copied. Sorry, now work perfectly.

**Comment by fvanroie** [comment]
Great, thanks for your feedback.
